# Generated by Django 3.2.16 on 2025-11-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postcomments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='post',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='post_id',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
            preserve_default=False,
        ),
    ]
