# Generated by Django 3.2.16 on 2025-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20251123_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='post_id',
            new_name='post',
        ),
    ]
